### ISSUE TITLE
How to setup?

### ISSUE THREAD

**Issue by zelda0079** [iamironman0/OpenAI-Whisper-GUI#11]
X:\XXX\OpenAI-Whisper-GUI-main>python setup.py
Traceback (most recent call last):
  File "D:\downloads_WD\chrome\OpenAI-Whisper-GUI-main\setup.py", line 12, in <module>
    import pkg_resources
  File "D:\ProgramFile\Python\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

**Comment by iamironman0** [comment]
Which python version do you use?

**Comment by zelda0079** [comment]
> Which python version do you use?

Python 3.12.1

**Comment by iamironman0** [comment]
Use older version, 3.11 or 3.10 is recommended.
